import type { Metadata } from "next";
import { Figtree, Lora } from "next/font/google";
import "./globals.css";

const figTree = Figtree({ subsets: ["latin"], variable: "--font-figtree" });
const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "LMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${figTree.variable} ${figTree.className} overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
